export const images = {
    appLogo: require('../assests/images/logo.png'),
    backgroundSpalsh: require('../assests/images/Background_Spalsh.png'),
    avtarImg: require('../assests/images/avtar.png'),
    callImg: require('../assests/images/Icon_Phone.png'),
    messageImg: require('../assests/images/Icon_Chat.png'),
    sourceImg: require('../assests/images/source.png'),
    destination: require('../assests/images/Vector.png'),
    locationImg: require('../assests/images/destination.png'),
    filter: require('../assests/images/filter.png'),
    people: require('../assests/images/people.png'),
    forward: require('../assests/images/forword.png'),
    map: require('../assests/images/map.png'),
    codes: require('../assests/images/codes.png'),
    bath: require('../assests/images/bath.png'),
    misc: require('../assests/images/misc.png'),
    photos: require('../assests/images/photos.png'),
    dataNotFound: require('../assests/images/dataNotFound.png'),
    notFound: require('../assests/images/notFound.png'),
    backIcon: require('../assests/images/back.png'),
    SourceAvtar: require('../assests/images/SourceAvtar.png'),
    House: require('../assests/images/House.png'),
    CircleHouse: require('../assests/images/CircleHouse.png'),
    Info: require('../assests/images/info.png'),
    HomeDestination: require('../assests/images/HomeDestination.png'),
    sliderImg1: require('../assests/images/sliderImg1.png'),
    ForwordArrow: require('../assests/images/ForwordArrow.png'),
    BackArrow: require('../assests/images/BackArrow.png'),
    Home2: require('../assests/images/Home2.jpg'),
    Home1: require('../assests/images/Home1.jpg'),

};


